import { Righteous } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Container from "@/components/Container";
import TranslationProvider from "@/components/TranslationProvider";

const righteous = Righteous({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Travel World",
  description: "Generated by create next app",
};

function RootLayout({ children, lang }) {
  const direction = lang === "ar" ? "rtl" : "ltr";
  return (
    <html lang={lang} dir={direction}>
      <TranslationProvider>
        <body className={`${righteous.className} overflow-x-hidden`}>
          <Container>
            <Navbar />
          </Container>
          {children}
        </body>
      </TranslationProvider>
    </html>
  );
}

export default RootLayout;
